"""Example model

Revision ID: f28726f89241
Revises: 
Create Date: 2021-12-06 23:23:21.879919

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = 'f28726f89241'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_example_active'), 'example', ['active'], unique=False)
    op.create_index(op.f('ix_example_id'), 'example', ['id'], unique=False)
    op.create_index(op.f('ix_example_name'), 'example', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_example_name'), table_name='example')
    op.drop_index(op.f('ix_example_id'), table_name='example')
    op.drop_index(op.f('ix_example_active'), table_name='example')
    op.drop_table('example')
    # ### end Alembic commands ###
